version: '3.8'
services:
  movies:
    image: sreevanga/datascience:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
    volumes:
      - "movies"
  train:
    image: sreevanga/aws:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
    volumes:
      - "train"
  dth:
    image: sreevanga/azure:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
    volumes:
      - "dth"
  recharge:
    image: sreevanga/GCP:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
    volumes:
      - "recharge"
