version: '3.8'
services:
  datascience:
    image: sreevanga/datascience:latest
    ports:
      - "85:80"
    deploy:
      replicas: 3
  aws:
    image: sreevanga/aws:latest
    ports:
      - "87:80"
    deploy:
      replicas: 3
  azure:
    image: sreevanga/azure:latest
    ports:
      - "88:80"
    deploy:
      replicas: 3
  gcp:
    image: sreevanga/gcp:latest
    ports:
      - "86:80"
    deploy:
      replicas: 3
