version: '3.8'
services:
  datascience:
    image: sreevanga/datascience:latest
    ports:
      - "85:80"
    deploy:
      replicas: 3
    volumes:
      - "movies"
  aws:
    image: sreevanga/aws:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
    volumes:
      - "train"
  azure:
    image: sreevanga/azure:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
    volumes:
      - "dth"
  gcp:
    image: sreevanga/gcp:latest
    ports:
      - "86:80"
    deploy:
      replicas: 3
    volumes:
      - "recharge"
